// Gamepad button layout lookup table for Linux and Android.
// This file was generated by gamepads.py,
// using data derived from 'gamecontrollerdb.txt'.
// - Duplicates and problematic items were discarded.
// - Controllers with missing buttons were discarded.

#if defined(__linux__) && !defined(__ANDROID__)  // Linux, but not Android
#define LINUX
#endif

#if !defined(__linux__)  // Not for Win32
#define GAMEPAD_H
#endif

#ifndef GAMEPAD_H
#define GAMEPAD_H

#include <array>
#include <cstdint>

#ifdef LINUX
constexpr std::array gamepad_layout_list = {
//   A   B   X   Y   LB  RB  LS  RS  UP  DN  LE  RI  THUMBL  THUMBR  TRIGER  SEL START
    "b0  b1  b2  b3  b4  b5  b9  b10 h   h   h   h   a0  a1  a3  a4  a2  a5  b6  b7  ",  // 0
    "b1  b2  b0  b3  b4  b5  b10 b11 h   h   h   h   a0  a1  a2  a3  b6  b7  b8  b9  ",  // 1
    "b0  b1  b3  b4  b6  b7  b13 b14 h   h   h   h   a0  a1  a2  a3  a5  a4  b10 b11 ",  // 2
    "b1  b2  b0  b3  b4  b5  b10 b11 h   h   h   h   a0  a1  a2  a5  a3  a4  b8  b9  ",  // 3
    "b2  b1  b3  b0  b4  b5  b10 b11 h   h   h   h   a0  a1  a2  a3  b6  b7  b8  b9  ",  // 4
    "b1  b0  b4  b3  b6  b7  b13 b14 h   h   h   h   a0  a1  a2  a3  b8  b9  b10 b11 ",  // 5
    "b0  b1  b2  b3  b4  b5  b10 b11 h   h   h   h   a0  a1  a2  a3  b6  b7  b8  b9  ",  // 6
    "b1  b0  b4  b3  b6  b7  b13 b14 h   h   h   h   a0  a1  a2  a3  a5  a4  b10 b11 ",  // 7
    "b0  b1  b3  b4  b6  b7  b13 b14 h   h   h   h   a0  a1  a2  a3  b8  b9  b10 b11 ",  // 8
    "b1  b2  b0  b3  b4  b5  b10 b11 h   h   h   h   a0  a1  a2  a5  b6  b7  b8  b9  ",  // 9
    "b0  b1  b2  b3  b4  b5  b7  b8  h   h   h   h   a0  a1  a2  a3  a5  a4  b9  b6  ",  // 10
    "b2  b3  b0  b1  b4  b6  b10 b11 h   h   h   h   a0  a1  a3  a2  b5  b7  b8  b9  ",  // 11
    "b0  b1  b2  b3  b4  b5  b9  b10 h   h   h   h   a0  a1  a2  a3  a5  a4  b6  b7  ",  // 12
    "b2  b3  b0  b1  b4  b5  b8  b9  h   h   h   h   a0  a1  a3  a2  b6  b7  b10 b11 ",  // 13
    "b0  b1  b3  b4  b5  b2  b8  b9  h   h   h   h   a0  a1  a3  a4  a2  a5  b6  b7  ",  // 14
    "b14 b13 b15 b12 b10 b11 b1  b2  b4  b6  b7  b5  a0  a1  a2  a3  b8  b9  b0  b3  ",  // 15
    "b0  b1  b2  b3  b4  b5  b9  b10 b13 b14 b11 b12 a0  a1  a3  a4  a2  a5  b6  b7  ",  // 16
    "b0  b2  b1  b3  b4  b6  b10 b11 h   h   h   h   a0  a1  a2  a3  b5  b7  b8  b9  ",  // 17
    "b1  b0  b4  b3  b6  b7  b13 b14 h   h   h   h   a0  a1  a3  a4  b8  b9  b10 b11 ",  // 18
    "b2  b1  b3  b0  b6  b7  b10 b11 h   h   h   h   a0  a1  a2  a3  b4  b5  b9  b8  ",  // 19
    "b0  b1  b3  b4  b6  b7  b12 b13 h   h   h   h   a0  a1  a2  a3  a5  a4  b10 b11 ",  // 20
    "b0  b1  b2  b3  b4  b5  b11 b12 h   h   h   h   a0  a1  a2  a3  b6  b7  b8  b9  ",  // 21
    "b0  b1  b3  b2  b5  b6  b12 b13 b14 b15 b16 b17 a0  a1  a2  a3  b7  b8  b9  b10 ",  // 22
    "b0  b1  b2  b3  b4  b5  b8  b9  h   h   h   h   a0  a1  a2  a5  a3  a4  b6  b7  ",  // 23
    "b2  b1  b3  b0  b6  b7  b10 b11 h   h   h   h   a0  a1  a3  a2  b4  b5  b8  b9  ",  // 24
    "b1  b0  b4  b3  b6  b7  b13 b14 h   h   h   h   a0  a1  a2  a3  a4  a5  b10 b11 ",  // 25
    "b1  b2  b0  b3  b4  b5  b10 b11 h   h   h   h   a0  a1  a3  a2  b6  b7  b8  b9  ",  // 26
    "b0  b1  b2  b3  b4  b5  b10 b11 h   h   h   h   a0  a1  a2  a3  a5  a4  b8  b9  ",  // 27
    "b0  b1  b3  b4  b6  b7  b13 b14 h   h   h   h   a0  a1  a2  a3  a6  a5  b17 b11 ",  // 28
    "b0  b1  b2  b3  b4  b5  b7  b8  h   h   h   h   a0  a1  a2  a5  a3  a4  b14 b6  ",  // 29
    "b1  b2  b0  b3  b4  b5  b10 b11 h   h   h   h   a0  a1  a2  a4  b6  b7  b8  b9  ",  // 30
    "b0  b1  b2  b3  b4  b5  b10 b11 h   h   h   h   a0  a1  a2  a5  a3  a4  b6  b7  ",  // 31
    "b1  b0  b3  b4  b6  b7  b13 b14 h   h   h   h   a0  a1  a2  a4  b8  b9  b10 b11 ",  // 32
    "b0  b1  b2  b3  b4  b5  b6  b7  h   h   h   h   a0  a1  a2  a3  a5  a4  b9  b8  ",  // 33
    "b0  b1  b3  b2  b4  b5  b9  b10 h   h   h   h   a0  a1  a3  a4  a2  a5  b6  b7  ",  // 34
    "b0  b1  b2  b3  b4  b6  b12 b11 h   h   h   h   a0  a1  a3  a2  b5  b7  b8  b10 ",  // 35
    "b5  b3  b4  b2  b8  b9  b10 b11 h   h   h   h   a0  a1  a2  a3  b6  b7  b12 b13 ",  // 36
    "b1  b2  b0  b3  b4  b5  b10 b11 h   h   h   h   a0  a1  a2  a4  a3  -a3 b8  b9  ",  // 37
    "b2  b3  b0  b1  b4  b5  b8  b9  h   h   h   h   a0  a1  a2  a3  b6  b7  b10 b11 ",  // 38
    "b2  b1  b3  b0  b6  b7  b10 b11 b12 b14 b15 b13 a0  a1  a5  a2  b4  b5  b8  b9  ",  // 39
    "b0  b1  b3  b4  b6  b7  b13 b16 h   h   h   h   a0  a1  a2  a3  b8  b9  b10 b11 ",  // 40
    "b2  b1  b3  b0  b6  b7  b9  b10 h   h   h   h   a0  a1  a3  a2  b4  b5  b8  b11 ",  // 41
    "b0  b1  b2  b3  b4  b6  b10 b11 h   h   h   h   a0  a1  a3  a2  b5  b7  b8  b9  ",  // 42
    "b0  b2  b1  b3  b10 b11 b8  b9  b4  b5  b6  b7  a0  a1  a2  a5  a3  a4  b17 b16 ",  // 43
    "b1  b0  b3  b2  b10 b11 b8  b9  b4  b5  b6  b7  a0  a1  a2  a5  a3  a4  b17 b16 ",  // 44
    "b0  b1  b2  b3  b4  b5  b9  b10 h   h   h   h   a0  a1  a3  a4  a2  a5  b6  b7  ",  // 45
    "b3  b4  b0  b1  b6  b7  b2  b5  h   h   h   h   a0  a1  a2  a3  b8  b9  b10 b11 ",  // 46
    "b2  b1  b3  b0  b4  b5  b10 b11 h   h   h   h   a0  a1  a3  a2  b6  b7  b8  b9  ",  // 47
    "b0  b1  b2  b3  b4  b5  b9  b10 h   h   h   h   a0  a1  a4  a4  a2  a5  b6  b7  ",  // 48
    "b2  b3  b0  b1  b4  b6  b10 b11 h   h   h   h   a0  a1  a2  a3  b5  b7  b8  b9  ",  // 49
    "b0  b1  b2  b3  b12 b4  b15 b7  b11 b8  b10 b9  a0  a1~ a2  a3~ b13 b5  b14 b6  ",  // 50
    "b1  b0  b3  b2  b9  b10 b7  b8  b11 b12 b13 b14 a0  a1  a2  a3  a4  a5  b4  b6  ",  // 51
    "b0  b1  b3  b2  b4  b5  b11 b12 b13 b14 b15 b16 a0  a1  a2  a3  b6  b7  b8  b9  ",  // 52
    "b0  b1  b2  b3  b4  b5  b8  b9  h   h   h   h   a0  a1  a2  a3  a5  a4  __  b7  ",  // 53
    "b0  b1  b2  b3  b4  b5  b11 b12 h   h   h   h   a0  a1  a3  a2  b6  b7  b8  b9  ",  // 54
    "b0  b3  b1  b2  b4  b5  b6  b7  b8  b9  b10 b11 a0  a1  a3  a4  a2  a5  __  __  ",  // 55
    "b0  b1  b2  b3  b4  b5  b9  b10 b14 b13 b14 b13 a0  a1  a3  a4  a2  a5  b6  b7  ",  // 56
    "b1  b0  b2  b3  b4  b5  b10 b11 h   h   h   h   a0  a1  a2  a3  b6  b7  b8  b9  ",  // 57
    "b0  b1  b3  b2  b4  b5  b11 b12 h   h   h   h   a0  a1  a3  a4  a2  a5  b8  b9  ",  // 58
    "b1  b2  b0  b3  b4  b5  b10 b11 h   h   h   h   a0  a1  a2  a5  b6  a4  b8  b9  ",  // 59
    "b0  b1  b2  b3  b4  b5  b8  b9  h   h   h   h   a0  a1  a2  a3  b6  b7  b10 b11 ",  // 60
    "b2  b3  b1  b0  b4  b5  b10 b11 h   h   h   h   a0  a1  a2  a3  b6  b7  b8  b9  ",  // 61
    "b1  b2  b0  b3  b6  b7  b10 b11 h   h   h   h   a0  a1  a3  a2  b4  b5  b8  b12 ",  // 62
    "b1  b2  b0  b3  b4  b5  b10 b11 h   h   h   h   a0  a1  a3  a4  a2  b7  b8  b9  ",  // 63
    "b2  b1  b3  b0  b6  b7  b9  b10 b12 b14 b15 b13 a0  a1  a2  a3  b4  b5  b8  b11 ",  // 64
    "b0  b1  b3  b4  b6  b7  b13 b14 h   h   h   h   a0  a1  a2  a3  a2  a3  b10 b11 ",  // 65
    "b2  b1  b3  b0  b6  b7  b10 b11 b12 b14 b15 b13 a0  a1  a2  a3  b4  b5  b9  b8  ",  // 66
    "b0  b1  b3  b2  b4  b5  b10 b11 h   h   h   h   a0  a1  a5  a2  b6  b7  b8  b9  ",  // 67
    "b0  b2  b1  b3  b4  b6  b10 b11 h   h   h   h   a0  a1  a2  a3  b8  b9  __  __  ",  // 68
    "b0  b2  b1  b3  b4  b6  b11 b12 h   h   h   h   a0  a1  a2  a3  b5  b7  b9  b10 ",  // 69
    "b2  b1  b3  b0  b4  b5  b10 b11 h   h   h   h   a0  a1  a3  a4  b6  b7  b8  b9  ",  // 70
    "b2  b3  b4  b5  b6  b7  b13 b14 -a5 a5  -a4 a4  a0  a1  a2  a3  a7  a6  b10 b11 ",  // 71
    "b0  b1  b2  b3  b6  b7  b10 b11 h   h   h   h   a0  a1  a3  a2  b4  b5  b8  b9  ",  // 72
    "b1  b0  b3  b2  b4  b5  b11 b12 h   h   h   h   a0  a1  a2  a3  b6  b7  b8  b9  ",  // 73
    "b0  b1  b2  b3  b4  b5  b8  b9  h   h   h   h   a0  a1  a3  a4  a2  a5  b6  b7  ",  // 74
    "b0  b1  b3  b4  b6  b7  b13 b14 h   h   h   h   a0  a1  a2  a5  a7  a6  b10 b11 ",  // 75
};

static struct gamepad_index {
    uint16_t VID;     // Vendor ID
    uint16_t PID;     // Product ID
    uint8_t  BUS;     // USB(3) or Bluetooth(5)
    uint8_t  inx;     // Layout index
} gamepad_index[] = {
    {0x0079,0x18d4,3, 0},  // USB: GPD Win 2 Controller
    {0x044f,0xb326,3, 0},  // USB: Thrustmaster GP XID
    {0x045e,0x028e,3, 0},  // USB: Be1 GC101 Xbox 360 Controller
    {0x045e,0x028e,5, 0},  // BT : Microsoft Xbox One Elite 2
    {0x045e,0x02d1,3, 0},  // USB: Microsoft Xbox One Controller
    {0x045e,0x02dd,3, 0},  // USB: Microsoft Xbox One Controller
    {0x045e,0x02dd,6, 0},  // VRT: Xbox One Controller
    {0x045e,0x02e3,3, 0},  // USB: Microsoft Xbox One Elite
    {0x045e,0x02ea,3, 0},  // USB: Microsoft Xbox One Controller
    {0x045e,0x02ea,6, 0},  // VRT: Xbox One Controller
    {0x045e,0x0b00,3, 0},  // USB: Microsoft Xbox One Elite 2
    {0x045e,0x0b12,3, 0},  // USB: Microsoft Xbox Series Controller
    {0x045e,0x0b12,6, 0},  // VRT: Microsoft Xbox One Controller
    {0x046d,0xc21d,3, 0},  // USB: Logitech F310
    {0x046d,0xc21e,3, 0},  // USB: Logitech F510
    {0x046d,0xc21f,3, 0},  // USB: Logitech F710
    {0x0738,0x4716,3, 0},  // USB: Mad Catz Xbox 360 Controller
    {0x0e6f,0x011f,3, 0},  // USB: Rock Candy
    {0x0e6f,0x0131,3, 0},  // USB: PDP EA Sports Controller
    {0x0e6f,0x0139,3, 0},  // USB: Afterglow Prismatic Controller
    {0x0e6f,0x0164,3, 0},  // USB: PDP Battlefield One
    {0x0e6f,0x0213,3, 0},  // USB: Afterglow Xbox 360 Controller
    {0x0e6f,0x02a7,3, 0},  // USB: PDP Xbox One Raven Black
    {0x0e6f,0x02b8,3, 0},  // USB: PDP Afterglow Xbox One Controller
    {0x0e6f,0x02c8,3, 0},  // USB: PDP Kingdom Hearts Controller
    {0x0e6f,0x02d8,3, 0},  // USB: PDP Xbox Series Controller
    {0x0e6f,0x02da,3, 0},  // USB: Logic3 Afterglow Xbox Series Controller
    {0x0e6f,0x02ef,3, 0},  // USB: PDP Xbox Series Kinetic Controller
    {0x0e6f,0x02f1,3, 0},  // USB: PDP Xbox Atomic
    {0x0e6f,0x0301,3, 0},  // USB: Logic3 Controller
    {0x0e6f,0x0315,3, 0},  // USB: Xbox 360 Controller
    {0x0e6f,0x0401,3, 0},  // USB: Gamestop Logic3 Controller
    {0x0e6f,0x0413,3, 0},  // USB: Xbox Controller
    {0x0e6f,0xf501,3, 0},  // USB: Logic3 Gamepad
    {0x0f0d,0x0067,3, 0},  // USB: Horipad One
    {0x0f0d,0x0150,3, 0},  // USB: Hori Fighting Commander Octa Xbox One
    {0x0f0d,0x0185,3, 0},  // USB: Hori Split Pad Fit
    {0x1038,0x1430,3, 0},  // USB: SteelSeries Stratus Duo
    {0x1038,0x1431,3, 0},  // USB: SteelSeries Stratus Duo
    {0x10f5,0x7008,6, 0},  // VRT: Turtle Beach Recon
    {0x10f5,0x7013,3, 0},  // USB: Turtle Beach ReactR
    {0x146b,0x0609,3, 0},  // USB: Nacon Asymmetric PS4 Controller
    {0x1532,0x0a03,3, 0},  // USB: Razer Wildcat
    {0x1532,0x0a14,3, 0},  // USB: Razer Wolverine Ultimate Xbox
    {0x1689,0xfe00,3, 0},  // USB: Razer Sabertooth
    {0x1bad,0xf016,3, 0},  // USB: Mad Catz Xbox 360 Controller
    {0x1bad,0xf501,3, 0},  // USB: Hori Pad EX Turbo 2
    {0x20d6,0x2002,3, 0},  // USB: PowerA Xbox One Controller
    {0x20d6,0x2005,3, 0},  // USB: PowerA Xbox Series Controller
    {0x20d6,0x200b,3, 0},  // USB: PowerA Xbox Series Controller
    {0x20d6,0x200f,3, 0},  // USB: PowerA Xbox Series Controller
    {0x20d6,0x2065,3, 0},  // USB: PowerA Xbox Series Controller
    {0x20d6,0x2802,3, 0},  // USB: PowerA Xbox One Controller
    {0x20d6,0x4001,3, 0},  // USB: PowerA Fusion Pro 2 Controller
    {0x20d6,0x4002,3, 0},  // USB: PowerA Xbox One Spectra Infinity
    {0x20d6,0x4005,3, 0},  // USB: PowerA Advantage Xbox Series Controller
    {0x24c6,0x5300,3, 0},  // USB: PowerA
    {0x24c6,0x531a,3, 0},  // USB: PowerA Mini Pro Ex
    {0x24c6,0x541a,3, 0},  // USB: PowerA Xbox One Mini Controller
    {0x24c6,0x543a,3, 0},  // USB: PowerA 1428124-01
    {0x24c6,0x581a,3, 0},  // USB: PowerA Xbox One Controller
    {0x24c6,0x5b02,3, 0},  // USB: Thrustmaster GPX
    {0x24c6,0x5d04,3, 0},  // USB: Razer Sabertooth
    {0x24c6,0xfafe,3, 0},  // USB: Rock Candy Xbox 360 Controller
    {0x28de,0x11ff,3, 0},  // USB: Steam Virtual Gamepad
    {0x294b,0x3004,3, 0},  // USB: Snakebyte Xbox Series Controller
    {0x2dc8,0x2000,3, 0},  // USB: 8BitDo Pro 2 for Xbox
    {0x2dc8,0x2000,6, 0},  // VRT: 8BitDo Pro 2 for Xbox
    {0x2dc8,0x2003,6, 0},  // VRT: 8BitDo Ultimate C Xbox Controller
    {0x2dc8,0x2019,3, 0},  // USB: 8BitDo Ultimate Mini Wired Controller for Xbox
    {0x2dc8,0x2025,3, 0},  // USB: 8BitDo Ultimate C Xbox Controller
    {0x2dc8,0x3106,3, 0},  // USB: 8BitDo Adapter 2
    {0x2dc8,0x310a,3, 0},  // USB: 8BitDo Ultimate 2C
    {0x2dc8,0x310b,3, 0},  // USB: 8BitDo Ultimate 2
    {0x2e24,0x1128,3, 0},  // USB: Hyperkin Competitor
    {0x2e24,0x1688,3, 0},  // USB: Hyperkin X91
    {0x2f24,0x0091,3, 0},  // USB: EasySMX ESM-9101
    {0x2f24,0x00f7,3, 0},  // USB: Mayflash Magic S Pro
    {0x3285,0x0607,3, 0},  // USB: Nacon GC100
    {0x3537,0x1004,3, 0},  // USB: GameSir T4 Kaleid
    {0x3537,0x100b,3, 0},  // USB: GameSir Cyclone 2
    {0x37d7,0x2414,3, 0},  // USB: Flydigi Direwolf 4
    {0xdead,0xbeef,6, 0},  // VRT: Hidromancer Controller
    {0xfade,0xc001,3, 0},  // USB: Flydigi Vader 5 Pro
    {0x0079,0x1800,3, 1},  // USB: Mayflash Wii U Pro Adapter
    {0x0079,0x181a,3, 1},  // USB: Venom PS4 Arcade Joystick
    {0x0079,0x18d2,3, 1},  // USB: Mayflash Magic NS
    {0x044f,0xd007,3, 1},  // USB: Thrustmaster T Mini
    {0x044f,0xd009,3, 1},  // USB: Thrustmaster Run N Drive PlayStation Controller
    {0x046d,0xc216,3, 1},  // USB: Logitech Dual Action
    {0x046d,0xc218,3, 1},  // USB: Logitech RumblePad 2
    {0x046d,0xc219,3, 1},  // USB: Logitech F710
    {0x046d,0xcad1,3, 1},  // USB: Logitech Chillstream
    {0x046d,0xcad2,3, 1},  // USB: Precision Controller
    {0x0738,0x3180,3, 1},  // USB: Mad Catz FightStick Alpha PS3
    {0x0738,0x3250,3, 1},  // USB: Mad Catz Fightpad Pro PS3
    {0x0738,0x3384,3, 1},  // USB: Mad Catz Fightstick TE S PS3
    {0x0738,0x5266,5, 1},  // BT : Mad Catz CTRLR
    {0x0738,0x8180,3, 1},  // USB: Mad Catz FightStick Alpha PS4
    {0x0c12,0x0e21,3, 1},  // USB: Brook Mars PS4 Controller
    {0x0c12,0x0e30,3, 1},  // USB: Brook Audio Fighting Board PS3
    {0x0e6f,0x011e,3, 1},  // USB: Rock Candy PS3 Controller
    {0x0e6f,0x0128,3, 1},  // USB: PDP PS3 Rock Candy Controller
    {0x0e6f,0x012f,3, 1},  // USB: PDP PS3 Controller
    {0x0e6f,0x0130,3, 1},  // USB: EA Sports PS3 Controller
    {0x0e6f,0x0180,3, 1},  // USB: Faceoff Pro Nintendo Switch Controller
    {0x0e6f,0x0181,3, 1},  // USB: Faceoff Deluxe Pro Nintendo Switch Controller
    {0x0e6f,0x0184,3, 1},  // USB: Faceoff Deluxe Nintendo Switch Controller
    {0x0e6f,0x0187,3, 1},  // USB: Rock Candy Nintendo Switch Controller
    {0x0e6f,0x0188,3, 1},  // USB: Afterglow Deluxe Nintendo Switch Controller
    {0x0e6f,0x0214,3, 1},  // USB: PS3 Controller
    {0x0e8f,0x310d,3, 1},  // USB: SZMY Power 3 Turbo
    {0x0e8f,0x3114,3, 1},  // USB: SZMY Power PS3
    {0x0f0d,0x0009,3, 1},  // USB: Natec Genesis P44
    {0x0f0d,0x0011,3, 1},  // USB: Hori Real Arcade Pro 3
    {0x0f0d,0x004d,3, 1},  // USB: Hori Gem Pad 3
    {0x0f0d,0x006b,3, 1},  // USB: Hori Real Arcade Pro 4
    {0x0f0d,0x006e,3, 1},  // USB: Horipad 4 PS3
    {0x0f0d,0x0085,3, 1},  // USB: Hori Fighting Commander PS3
    {0x0f0d,0x00c1,3, 1},  // USB: Horipad Nintendo Switch Controller
    {0x11c0,0x5503,3, 1},  // USB: Acrux Gamepad
    {0x12bd,0xc003,3, 1},  // USB: Joypad Alpha Shock
    {0x146b,0x0902,3, 1},  // USB: Bigben
    {0x1532,0x0402,3, 1},  // USB: Razer Panthera PS3
    {0x1a34,0x0836,3, 1},  // USB: PS3 Controller
    {0x20bc,0x5656,3, 1},  // USB: GameSir T4w
    {0x20d6,0xa710,3, 1},  // USB: Mayflash Magic NS
    {0x20d6,0xa711,3, 1},  // USB: PowerA Core Controller
    {0x20d6,0xa712,3, 1},  // USB: PowerA Fusion Nintendo Switch Fight Pad
    {0x20d6,0xa713,3, 1},  // USB: PowerA Nintendo Switch Controller
    {0x20d6,0xa714,3, 1},  // USB: PowerA Spectra Nintendo Switch Controller
    {0x20d6,0xca6d,3, 1},  // USB: PowerA Pro Ex
    {0x2185,0x0102,3, 1},  // USB: FF GP1
    {0x25f0,0x83c1,3, 1},  // USB: Goodbetterbest Controller
    {0x25f0,0x83c2,3, 1},  // USB: Gioteck VX2 PS3 Controller
    {0x2c22,0x2302,3, 1},  // USB: Qanba Obsidian Arcade Joystick PS3
    {0x2c22,0x2502,3, 1},  // USB: Qanba Dragon Arcade Joystick PS3
    {0x62dd,0xa715,3, 1},  // USB: PowerA Fusion Nintendo Switch Arcade Stick
    {0x62dd,0xa716,3, 1},  // USB: PowerA Fusion Pro Nintendo Switch Controller
    {0x6469,0x6469,5, 1},  // BT : idroidcon Controller
    {0x0111,0x1419,5, 2},  // BT : SteelSeries Stratus XL
    {0x0111,0x1431,5, 2},  // BT : SteelSeries Stratus Duo
    {0x03f0,0x038d,3, 2},  // USB: HyperX Clutch
    {0x03f0,0x048d,5, 2},  // BT : HyperX Clutch
    {0x045e,0x02fd,5, 2},  // BT : Xbox One Controller
    {0x045e,0x0b13,3, 2},  // USB: Xbox Series Controller
    {0x045e,0x0b13,5, 2},  // BT : Xbox Series Controller
    {0x045e,0x0b20,5, 2},  // BT : Xbox One Controller
    {0x045e,0x0b22,5, 2},  // BT : Xbox One Controller
    {0x0502,0x1309,3, 2},  // USB: Anbernic RG P01
    {0x05ac,0x022d,5, 2},  // BT : GameSir G4s
    {0x05ac,0x061a,3, 2},  // USB: GameSir T3 2.02
    {0x0b05,0x7905,3, 2},  // USB: ASUS ROG Kunai 3
    {0x0b05,0x7906,5, 2},  // BT : ASUS ROG Kunai 3
    {0x0f0d,0x0196,5, 2},  // BT : Horipad Steam
    {0x0f0d,0x01ab,3, 2},  // USB: Horipad Steam
    {0x1038,0x1441,5, 2},  // BT : SteelSeries Nimbus Cloud
    {0x11c3,0x9107,3, 2},  // USB: Be1 GC101 Controller 1.03
    {0x1532,0x0705,3, 2},  // USB: Razer Raiju Mobile
    {0x1915,0x7856,3, 2},  // USB: Uniplay U6
    {0x1949,0x0402,5, 2},  // BT : Amazon Fire Controller
    {0x1d5a,0x1802,5, 2},  // BT : Nokia GC 5000
    {0x20bc,0x5500,3, 2},  // USB: GameSir G3w
    {0x24c6,0x891a,5, 2},  // BT : MOGA XP5X Plus
    {0x24c6,0x891b,3, 2},  // USB: BDA MOGA XP5X Plus
    {0x24c6,0x892a,5, 2},  // BT : MOGA XP5A Plus
    {0x24c6,0x892b,3, 2},  // USB: MOGA XP5A Plus
    {0x2563,0x0526,3, 2},  // USB: ShanWan Gamepad
    {0x27f8,0x0bbf,3, 2},  // USB: Razer Kishi
    {0x2dc8,0x2101,3, 2},  // USB: 8BitDo Xbox One SN30 Pro
    {0x2dc8,0x2101,5, 2},  // BT : 8BitDo Xbox One SN30 Pro
    {0x2dc8,0x3011,3, 2},  // USB: 8BitDo Ultimate
    {0x2dc8,0x3012,3, 2},  // USB: 8BitDo Ultimate
    {0x2dc8,0x3012,5, 2},  // BT : 8BitDo Ultimate
    {0x2dc8,0x3013,3, 2},  // USB: 8BitDo Ultimate
    {0x2dc8,0x3015,3, 2},  // USB: 8BitDo Ultimate C
    {0x2dc8,0x3016,3, 2},  // USB: 8BitDo Ultimate C
    {0x2dc8,0x3017,3, 2},  // USB: 8BitDo Ultimate C
    {0x2dc8,0x301b,5, 2},  // BT : 8BitDo Ultimate 2C
    {0x2dc8,0x301d,3, 2},  // USB: 8BitDo Ultimate 2C
    {0x2dc8,0x6012,3, 2},  // USB: 8BitDo Ultimate 2
    {0x2dc8,0x6012,5, 2},  // BT : 8BitDo Ultimate 2
    {0x3285,0x0305,5, 2},  // BT : Nacon MGX Pro
    {0x3537,0x1007,3, 2},  // USB: Anbernic RG P01
    {0x3537,0x1046,5, 2},  // BT : Anbernic RG P01
    {0x3537,0x1058,3, 2},  // USB: GameSir K1
    {0x3537,0x1094,3, 2},  // USB: GameSir Tegenaria Lite
    {0x3537,0x1097,3, 2},  // USB: GameSir Kaleid Flux
    {0x358a,0x0102,3, 2},  // USB: Backbone One
    {0x358a,0x0202,3, 2},  // USB: Backbone One
    {0x358a,0x0203,3, 2},  // USB: Backbone One
    {0x358a,0x0204,3, 2},  // USB: Backbone One
    {0x0079,0x181b,3, 3},  // USB: Venom PS4 Arcade Joystick
    {0x044f,0xd00e,3, 3},  // USB: Thrustmaster eSwap Pro Controller
    {0x054c,0x05c4,5, 3},  // BT : PS4 Controller
    {0x054c,0x09cc,3, 3},  // USB: PS4 Controller
    {0x054c,0x09cc,5, 3},  // BT : PS4 Controller
    {0x054c,0x0ba0,3, 3},  // USB: PS4 Controller
    {0x054c,0x0ce6,3, 3},  // USB: PS5 Controller
    {0x054c,0x0ce6,5, 3},  // BT : PS5 Controller
    {0x054c,0x0df2,3, 3},  // USB: PS5 Controller
    {0x054c,0x0df2,5, 3},  // BT : PS5 Controller
    {0x054c,0x0e5f,3, 3},  // USB: PS5 Access Controller
    {0x0738,0x8250,3, 3},  // USB: Mad Catz Fightpad Pro PS4
    {0x0738,0x8384,3, 3},  // USB: Mad Catz Fightstick TE S PS4
    {0x0c12,0x0e10,3, 3},  // USB: Zeroplus P4
    {0x0c12,0x0e20,3, 3},  // USB: Brook Mars PS4 Controller
    {0x0c12,0x0e31,3, 3},  // USB: Brook Audio Fighting Board PS4
    {0x0c12,0x1e10,3, 3},  // USB: Zeroplus P4
    {0x0c12,0x2e18,3, 3},  // USB: Zeroplus PS4 Controller
    {0x0f0d,0x0066,3, 3},  // USB: Horipad 4 PS4
    {0x0f0d,0x006a,3, 3},  // USB: Hori Real Arcade Pro 4
    {0x0f0d,0x0084,3, 3},  // USB: Hori Fighting Commander
    {0x0f0d,0x00ee,3, 3},  // USB: Horipad Mini 4
    {0x146b,0x0d01,3, 3},  // USB: Revolution Pro Controller
    {0x146b,0x0d13,3, 3},  // USB: Revolution Pro Controller 3
    {0x1532,0x0401,3, 3},  // USB: Razer Panthera PS4
    {0x1532,0x1000,3, 3},  // USB: Razer Raiju
    {0x1532,0x1008,3, 3},  // USB: Razer Panthera PS4 Evo Arcade Stick
    {0x1532,0x100a,5, 3},  // BT : Razer Raiju Tournament Edition
    {0x1532,0x100b,3, 3},  // USB: Razer Wolverine PS5 Controller
    {0x1532,0x1100,3, 3},  // USB: Razer Raion PS4 Fightpad
    {0x20d6,0x792a,3, 3},  // USB: BDA PS4 Fightpad
    {0x2c22,0x2300,3, 3},  // USB: Qanba Obsidian Arcade Joystick PS4
    {0x2c22,0x2500,3, 3},  // USB: Qanba Dragon Arcade Joystick PS4
    {0x3285,0x0d16,3, 3},  // USB: Nacon Revolution 5 Pro
    {0x3285,0x0d17,3, 3},  // USB: Nacon Revolution 5 Pro
    {0x3285,0x0d18,3, 3},  // USB: Nacon Revolution 5 Pro
    {0x3285,0x0d19,3, 3},  // USB: Nacon Revolution 5 Pro
    {0x7545,0x0104,3, 3},  // USB: SZMY Power DS4 Controller
    {0x05ac,0x055b,3, 4},  // USB: GameSir G3w
    {0x0e8f,0x0003,3, 4},  // USB: PS3 Controller
    {0x0e8f,0x0008,3, 4},  // USB: Gasia PlayStation Gamepad
    {0x0f0d,0x00aa,3, 4},  // USB: Hori Real Arcade Pro for Nintendo Switch
    {0x0f0d,0x00fb,3, 4},  // USB: Hori Hatsune Miku 39S
    {0x11c0,0x9105,3, 4},  // USB: Torid
    {0x11c1,0x9101,3, 4},  // USB: EasySMX
    {0x11c2,0x9107,3, 4},  // USB: Be1 GC101 Controller 1.03
    {0x11ff,0x3331,3, 4},  // USB: PC Controller
    {0x145f,0x01c5,3, 4},  // USB: Trust Gamepad
    {0x145f,0x0231,3, 4},  // USB: PS3 Controller
    {0x20bc,0x1264,3, 4},  // USB: Betop Controller
    {0x20e8,0x5860,3, 4},  // USB: Cideko AK08b
    {0x2563,0x0523,3, 4},  // USB: ShanWan Gamepad
    {0x2563,0x0575,3, 4},  // USB: Ipega PG 9099
    {0x2563,0x057a,3, 4},  // USB: Cosmic Byte Ares Controller
    {0x25f0,0x83c3,3, 4},  // USB: GT VX2
    {0x25f0,0xc121,3, 4},  // USB: Gioteck PS3 Controller
    {0x2f24,0x002d,3, 4},  // USB: JYS Adapter
    {0x3285,0x0c03,3, 4},  // USB: Nacon GC100
    {0x7545,0x1122,3, 4},  // USB: SZMY Power Gamepad
    {0x1002,0x9000,3, 5},  // USB: 8BitDo FC30 Pro
    {0x2002,0x9000,3, 5},  // USB: 8BitDo NES30 Pro
    {0x2dc8,0x2862,5, 5},  // BT : 8BitDo SN30 Pro
    {0x2dc8,0x2865,5, 5},  // BT : 8BitDo N30 Pro 2
    {0x2dc8,0x3101,3, 5},  // USB: 8BitDo Receiver
    {0x2dc8,0x3102,3, 5},  // USB: 8BitDo Receiver
    {0x2dc8,0x3103,3, 5},  // USB: 8BitDo Receiver
    {0x2dc8,0x3104,3, 5},  // USB: 8BitDo Receiver
    {0x2dc8,0x3810,5, 5},  // BT : 8BitDo FC30 Pro
    {0x2dc8,0x5111,3, 5},  // USB: 8BitDo Lite SE
    {0x2dc8,0x5111,5, 5},  // BT : 8BitDo Lite SE
    {0x2dc8,0x6000,3, 5},  // USB: 8BitDo SF30 Pro
    {0x2dc8,0x6000,5, 5},  // BT : 8BitDo SF30 Pro
    {0x2dc8,0x6002,3, 5},  // USB: 8BitDo SN30 Pro Plus
    {0x2dc8,0x6101,5, 5},  // BT : 8BitDo SN30 Pro
    {0x2dc8,0x6102,5, 5},  // BT : 8BitDo SN30 Pro Plus
    {0x2dc8,0x9015,3, 5},  // USB: 8BitDo N30 Pro 2
    {0x3820,0x0009,5, 5},  // BT : 8BitDo NES30 Pro
    {0x0079,0x0122,3, 6},  // USB: ZhiXu GuliKit D
    {0x057e,0x2009,5, 6},  // BT : Nintendo Switch Pro Controller
    {0x0c45,0x4320,3, 6},  // USB: XEOX SL6556 BK
    {0x0f0d,0x00f6,5, 6},  // BT : Horipad Switch Controller
    {0x10f5,0x018f,5, 6},  // BT : Turtle Beach Rematch Nintendo Switch Controller
    {0x11c9,0x55f0,3, 6},  // USB: HJC Gamepad
    {0x11ec,0xa7e1,3, 6},  // USB: Nintendo Switch
    {0x1345,0x1000,3, 6},  // USB: Genius Maxfire Grandias 12
    {0x146b,0x0c01,3, 6},  // USB: Nacon GC400ES
    {0x146b,0x5500,3, 6},  // USB: Bigben Interactive Gamepad
    {0x1a34,0x0809,3, 6},  // USB: SL6566
    {0x4f4d,0x4554,5, 6},  // BT : Mocute 053X
    {0x5347,0x6d61,5, 6},  // BT : GameStop Gamepad
    {0x694c,0x7250,5, 6},  // BT : Nintendo Switch Controller
    {0x2dc8,0x3010,3, 7},  // USB: 8BitDo Pro 2
    {0x2dc8,0x3820,5, 7},  // BT : 8BitDo NES30 Pro
    {0x2dc8,0x5112,3, 7},  // USB: 8BitDo Lite 2
    {0x2dc8,0x5112,5, 7},  // BT : 8BitDo Lite 2
    {0x2dc8,0x6006,3, 7},  // USB: 8BitDo Pro 2
    {0x2dc8,0x6006,5, 7},  // BT : 8BitDo Pro 2
    {0x2dc8,0x6007,3, 7},  // USB: 8BitDo Ultimate
    {0x2dc8,0x6009,3, 7},  // USB: 8BitDo Pro 3
    {0x2dc8,0x6009,5, 7},  // BT : 8BitDo Pro 3
    {0x2dc8,0x6100,5, 7},  // BT : 8BitDo SF30 Pro
    {0x0079,0x181c,3, 8},  // USB: Mobapad Chitu HD
    {0x04e8,0x046e,5, 8},  // BT : Mocute 053X M59
    {0x1949,0x0403,5, 8},  // BT : Ipega PG9099
    {0x20bc,0x504d,3, 8},  // USB: Beitong A1T2 BFM
    {0x20bc,0x5500,5, 8},  // BT : Betop AX1 BFM
    {0x2dc8,0x3100,3, 8},  // USB: 8BitDo Adapter
    {0x8555,0x061b,3, 8},  // USB: GameSir G4 Pro
    {0x044f,0xb323,3, 9},  // USB: Thrustmaster Dual Trigger PlayStation Controller
    {0x044f,0xd008,3, 9},  // USB: Thrustmaster Run N Drive PlayStation Controller
    {0x0c12,0x0e16,3, 9},  // USB: PS3 Controller
    {0x11c0,0x4001,3, 9},  // USB: PS4 Controller
    {0x1345,0x3008,3, 9},  // USB: Nyko CORE
    {0x2c22,0x2010,3, 9},  // USB: Qanba Drone 2 Arcade Joystick PS5
    {0x0171,0x0419,5,10},  // BT : Amazon Luna Controller
    {0x0b05,0x4500,5,10},  // BT : ASUS Gamepad
    {0x20d6,0x0dad,5,10},  // BT : Moga Pro
    {0x20d6,0x6271,5,10},  // BT : Moga Pro 2
    {0x20d6,0x89e5,5,10},  // BT : Moga 2
    {0x07b5,0x0312,3,11},  // USB: Mega World Logic 3 Controller
    {0x07b5,0x0315,3,11},  // USB: Impact
    {0x0f30,0x0110,3,11},  // USB: Jess Tech Dual Analog Rumble
    {0x0f30,0x0111,3,11},  // USB: Jess Tech Colour Rumble Pad
    {0x0f30,0x0112,3,11},  // USB: Saitek P380
    {0x1532,0x0900,3,12},  // USB: Razer Serval
    {0x1532,0x0900,5,12},  // BT : Razer Serval
    {0x18d1,0x9400,3,12},  // USB: Google Stadia Controller
    {0x18d1,0x9400,5,12},  // BT : Google Stadia Controller
    {0x05ef,0x0003,3,13},  // USB: InterAct AxisPad
    {0x06a3,0x0109,3,13},  // USB: Saitek P880
    {0x06a3,0xff0c,3,13},  // USB: Saitek P2500 Force Rumble
    {0x0c12,0x0005,3,13},  // USB: InterAct AxisPad
    {0x045e,0x0202,3,14},  // USB: Xbox Controller
    {0x045e,0x0285,3,14},  // USB: Microsoft Xbox Controller
    {0x045e,0x0289,3,14},  // USB: Microsoft Xbox Controller
    {0xffff,0xffff,3,14},  // USB: Xbox Controller
    {0x054c,0x0268,3,15},  // USB: PS3 Controller
    {0x054c,0x0268,5,15},  // BT : PS3 Controller
    {0x054c,0x0268,6,15},  // VRT: PS3 Controller
    {0x4c50,0x5453,5,15},  // BT : PS3 Controller
    {0x045e,0x0291,3,16},  // USB: Xbox 360 Controller
    {0x045e,0x02a1,3,16},  // USB: Xbox 360 Controller
    {0x045e,0x0719,3,16},  // USB: Xbox 360 Controller
    {0x1689,0xfd01,3,16},  // USB: Razer Onza Classic Edition
    {0x044f,0xb304,3,17},  // USB: Thrustmaster Firestorm Dual Power
    {0x044f,0xb312,3,17},  // USB: Thrustmaster Vibrating Gamepad
    {0x044f,0xb315,3,17},  // USB: Thrustmaster Dual Analog 3.2
    {0x044f,0xb320,3,17},  // USB: Thrustmaster Dual Trigger
    {0x2dc8,0x6001,3,18},  // USB: 8BitDo SN30 Pro
    {0x2dc8,0x6101,3,18},  // USB: 8BitDo SN30 Pro
    {0x2dc8,0x9012,3,18},  // USB: 8BitDo SN30 Pro
    {0x05e3,0x0732,3,19},  // USB: Austgame Twin Pad
    {0x0925,0x0005,3,19},  // USB: SmartJoy PlayStation Adapter
    {0x0925,0x8866,3,19},  // USB: MP8866 Super Dual Box
    {0x04b4,0x2411,3,20},  // USB: Flydigi Vader 2
    {0x04b4,0x2412,3,20},  // USB: Flydigi Vader 2
    {0x1915,0x0040,5,20},  // BT : Flydigi Vader 2
    {0x0001,0x0001,5,21},  // BT : Nintendo Wii Remote
    {0x0e6f,0x02a8,3,21},  // USB: PDP Xbox One Controller
    {0x0f0d,0x0086,3,21},  // USB: Hori Fighting Commander Xbox 360
    {0x057e,0x2006,6,22},  // VRT: Nintendo Switch Combined Joy-Cons
    {0x057e,0x2008,6,22},  // VRT: Nintendo Switch Combined Joy-Cons
    {0x694e,0x6e65,6,22},  // VRT: Nintendo Switch Combined Joy-Cons
    {0x2e95,0x434b,3,23},  // USB: Scuf Envision
    {0x2e95,0x434d,3,23},  // USB: Scuf Envision
    {0x2e95,0x434e,3,23},  // USB: Scuf Envision
    {0x04d9,0x0f16,3,24},  // USB: Sony PlayStation Adapter
    {0x0810,0x0001,3,24},  // USB: Twin PlayStation Adapter
    {0x0810,0x0003,3,24},  // USB: USB Gamepad
    {0x2dc8,0x9000,3,25},  // USB: 8BitDo FC30 Pro
    {0x2dc8,0x9001,3,25},  // USB: 8BitDo NES30 Pro
    {0x06a3,0x040b,3,26},  // USB: Saitek P990 Dual Analog
    {0x187c,0x0600,3,26},  // USB: Alienware Dual Compatible Game PlayStation Controller
    {0x04b4,0x2412,5,27},  // BT : Flydigi APEX 4
    {0x4f43,0x4e41,5,27},  // BT : VX Gaming Command Series
    {0x045e,0x02e3,5,28},  // BT : Xbox One Elite
    {0x045e,0x0b05,5,28},  // BT : Microsoft Xbox One Elite 2
    {0x0955,0x7214,3,29},  // USB: NVIDIA Controller
    {0x0955,0x7214,5,29},  // BT : NVIDIA Controller
    {0x06a3,0xf620,3,30},  // USB: Saitek PS2700 Rumble
    {0x06a3,0xf623,3,30},  // USB: Saitek Cyborg PlayStation Controller
    {0x1949,0x0419,3,31},  // USB: Amazon Luna Controller
    {0x1008,0x01e5,3,32},  // USB: Anbernic Handheld
    {0x3250,0x1002,3,33},  // USB: Atari VCS Modern Controller
    {0x3250,0x1002,5,34},  // BT : Atari VCS Modern Controller
    {0x050d,0x0803,3,35},  // USB: Belkin Nostromo N45
    {0x1dd8,0x000b,3,36},  // USB: Buffalo BSGP1601
    {0x06a3,0xf622,3,37},  // USB: Cyborg V3 Rumble
    {0x056e,0x2003,3,38},  // USB: Elecom U3613M
    {0x0b43,0x0003,3,39},  // USB: EMS Production PS2 Adapter
    {0x05ac,0x057a,3,40},  // USB: GameSir G5
    {0x0e8f,0x1006,3,41},  // USB: GreenAsia Electronics Controller
    {0x0e8f,0x0012,3,42},  // USB: GreenAsia Joystick
    {0x2e8a,0x10dd,3,43},  // USB: Hand Held Legend GC Ultimate
    {0x2e8a,0x10df,3,44},  // USB: Hand Held Legend ProGCC
    {0x0f0d,0x006d,3,45},  // USB: Hori EDGE 301
    {0x05fd,0x262a,3,46},  // USB: InterAct HammerHead FX
    {0x0f30,0x010b,3,47},  // USB: Jess Tech GGE909 PC Recoil
    {0x4131,0x3519,3,48},  // USB: LeadJoy Xeno Plus
    {0x07b5,0x004f,3,49},  // USB: Mega World Logic 3 Controller
    {0x057e,0x2069,3,50},  // USB: Nintendo Switch 2 Pro Controller
    {0x057e,0x2009,3,51},  // USB: Nintendo Switch Pro Controller
    {0x057e,0x0330,5,52},  // BT : Nintendo Wii U Pro Controller
    {0x0955,0x7210,3,53},  // USB: NVIDIA Controller
    {0x124b,0x4d01,3,54},  // USB: Nyko Airflo EX
    {0x2836,0x0001,5,55},  // BT : OUYA Controller
    {0x0e6f,0x02d7,3,56},  // USB: PDP Black Camo Xbox Series Controller
    {0x0e6f,0x0185,3,57},  // USB: PDP Fightpad Pro Gamecube Controller
    {0x054c,0x05c4,3,58},  // USB: PS4 Controller
    {0x2c22,0x2012,3,59},  // USB: Qanba Drone 2 Arcade Joystick PS4
    {0x0583,0x2050,3,60},  // USB: Rockfire PlayStation Bridge
    {0x0e6f,0x1113,3,61},  // USB: Saffun Controller
    {0x06a3,0x040c,3,62},  // USB: Saitek P2900
    {0x06a3,0xf518,3,63},  // USB: Saitek P3200 Rumble
    {0x6666,0x0667,3,64},  // USB: Sony PlayStation Adapter
    {0x1038,0x1412,5,65},  // BT : SteelSeries Free
    {0x6666,0x8804,3,66},  // USB: Super Joy Box 5 Pro
    {0x22ba,0x0107,3,67},  // USB: Technology Innovation PlayStation Adapter
    {0x044f,0xb303,3,68},  // USB: Thrustmaster Firestorm Dual Analog 2
    {0x044f,0xb300,3,69},  // USB: Thrustmaster Firestorm Dual Power
    {0x0079,0x0006,3,70},  // USB: USB Gamepad
    {0x28de,0x1201,3,71},  // USB: Valve Steam Controller
    {0x05ac,0x3232,5,72},  // BT : VR Box Controller
    {0x045e,0x0b0a,3,73},  // USB: Xbox One Controller
    {0x045e,0x02e0,5,74},  // BT : Xbox One Controller
    {0x2717,0x3144,5,75},  // BT : XiaoMi Controller
};

// For gamepads with no VID:PID, index by string name instead.
static struct gamepad_by_name {
    char name[17];       // Name string
    uint8_t  inx;        // Layout index
} gamepad_by_name[] = {
    {"Lic Pro Controll", 6},  // Lic Pro Controller
    {"Nintendo Wireles", 6},  // Nintendo Wireless Gamepad
    {"Wireless Gamepad", 6},  // Wireless Gamepad
};
#endif

#ifdef __ANDROID__
constexpr std::array gamepad_layout_list = {
//   A   B   X   Y   LB  RB  LS  RS  UP  DN  LE  RI  THUMBL  THUMBR  TRIGER  SEL START
    "b0  b1  b3  b4  b6  b7  b10 b11 b15 b16 b17 b18 a0  a1  a2  a3  a4  a5  b8  b12 ",  // 0
    "b1  b0  b4  b3  b6  b7  b10 b11 b15 b16 b17 b18 a0  a1  a2  a3  b2  b5  b8  b12 ",  // 1
    "b1  b0  b4  b3  b6  b7  b10 b11 b15 b16 b17 b18 a0  a1  a2  a3  a4  a5  b13 b12 ",  // 2
    "b0  b1  b3  b4  b6  b7  b10 b11 b15 b16 b17 b18 a0  a1  a2  a3  a5  a4  b13 b12 ",  // 3
    "b1  b0  b4  b3  b6  b7  b10 b11 b15 b16 b17 b18 a0  a1  a2  a3  a5  a4  b13 b12 ",  // 4
    "b0  b1  b3  b4  b6  b7  b10 b11 b15 b16 b17 b18 a0  a1  a3  a4  a2  a5  b8  b12 ",  // 5
    "b1  b0  b4  b3  b6  b7  b10 b11 b15 b16 b17 b18 a0  a1  a2  a3  b8  b9  b13 b12 ",  // 6
    "b0  b1  b3  b4  b6  b7  b10 b11 b15 b16 b17 b18 a0  a1  a2  a5  a3  a4  b13 b12 ",  // 7
    "b1  b2  b0  b3  b4  b5  b13 b12 b15 b16 b17 b18 a0  a1  a2  a3  b6  b7  b8  b9  ",  // 8
    "b1  b0  b3  b2  b4  b5  b8  b9  b15 b16 b17 b18 a0  a1  a3  a4  a2  a5  b6  b7  ",  // 9
    "b7  b1  b4  b12 b13 b14 b2  b5  h   h   h   h   a0  a1  a2  a3  b11 b6  b9  b8  ",  // 10
    "b1  b0  b3  b4  b6  b7  b10 b11 b15 b16 b17 b18 a0  a1  a2  a4  b2  b5  b8  b12 ",  // 11
    "b1  b0  b4  b3  b6  b7  b10 b11 b15 b16 b18 b17 a0  a1  a2  a3  a5  a4  b13 b12 ",  // 12
    "b0  b1  b4  b12 b13 b14 b2  b5  h   h   h   h   a0  a1  a2  a3  b11 b6  b9  b8  ",  // 13
    "b0  b1  b2  b3  b4  b5  b13 b12 b15 b16 b17 b18 a0  a1  a2  a3  b6  b7  b8  b9  ",  // 14
    "b1  b2  b0  b3  b4  b5  b13 b12 b15 b16 b17 b18 a0  a1  a2  a5  a3  a4  b8  b9  ",  // 15
    "b0  b1  b3  b4  b6  b7  b10 b11 b15 b16 b17 b18 a0  a1  a2  a3  b2  b5  b8  b12 ",  // 16
    "b0  b1  b3  b4  b6  b7  b10 b11 b15 b16 b17 b18 a0  a1  a2  a3  a5  a6  b13 b12 ",  // 17
    "b0  b1  b3  b4  b6  b7  b10 b11 b15 b16 b17 b18 a0  a1  a2  a5  a7  a6  b13 b12 ",  // 18
};

static struct gamepad_index {
    uint16_t VID;     // Vendor ID
    uint16_t PID;     // Product ID
    uint8_t  BUS;     // USB(3) or Bluetooth(5)
    uint8_t  inx;     // Layout index
} gamepad_index[] = {
    {0x045e,0x028e,5, 0},  // BT : Xbox 360 Controller
    {0x045e,0x02e0,5, 0},  // BT : Xbox One Controller
    {0x045e,0x02ea,5, 0},  // BT : Xbox One Controller
    {0x045e,0x02fd,5, 0},  // BT : Xbox One Controller
    {0x045e,0x0b13,5, 0},  // BT : Xbox Series Controller
    {0x04b4,0x2411,5, 0},  // BT : Flydigi Vader 2
    {0x054c,0x0268,5, 0},  // BT : PS3 Controller
    {0x054c,0x05c4,5, 0},  // BT : PS4 Controller
    {0x054c,0x09cc,5, 0},  // BT : PS4 Controller
    {0x0955,0x7203,5, 0},  // BT : NVIDIA Controller
    {0x0955,0x7210,5, 0},  // BT : NVIDIA Controller
    {0x1532,0x0705,5, 0},  // BT : Razer Raiju Mobile
    {0x1532,0x0707,5, 0},  // BT : Razer Raiju Mobile
    {0x1532,0x0900,5, 0},  // BT : Razer Serval
    {0x27f8,0x0bbf,5, 0},  // BT : Razer Kishi
    {0x2002,0x9000,5, 2},  // BT : 8BitDo NES30 Pro
    {0x2820,0x0009,5, 2},  // BT : 8BitDo SNES30
    {0x2dc8,0x2865,5, 2},  // BT : 8BitDo N30 Pro 2
    {0x2dc8,0x6100,5, 2},  // BT : 8BitDo SF30 Pro
    {0x3820,0x0009,5, 2},  // BT : 8BitDo NES30 Pro
    {0x20bc,0x5500,5, 3},  // BT : GameSir G3w
    {0x2dc8,0x6001,5, 4},  // BT : 8BitDo SN30 Pro
    {0x2dc8,0x9015,5, 4},  // BT : 8BitDo N30 Pro 2
    {0x045e,0x0b00,5, 5},  // BT : Xbox One Elite 2 Controller
    {0x045e,0x0b12,5, 5},  // BT : Xbox Series Controller
    {0x2dc8,0x6000,5, 6},  // BT : 8BitDo SF30 Pro
    {0x2dc8,0x6002,5, 6},  // BT : 8BitDo SN30 Pro Plus
    {0x02d6,0x89e5,5, 7},  // BT : GPD XD Plus
    {0x0955,0x7214,5, 7},  // BT : NVIDIA Controller
    {0x2dc8,0x301b,5,10},  // BT : 8BitDo Ultimate 2C
    {0x3537,0x1116,5,13},  // BT : GameSir X5 Lite
    {0x057e,0x2009,5,14},  // BT : Nintendo Switch Pro Controller
    {0x054c,0x0ce6,5,15},  // BT : PS5 Controller
    {0x045e,0x0b05,5,17},  // BT : Xbox One Elite 2 Controller
    {0x2717,0x3144,5,18},  // BT : XiaoMi Controller
};

// For gamepads with no VID:PID, index by string name instead.
static struct gamepad_by_name {
    char name[17];       // Name string
    uint8_t  inx;        // Layout index
} gamepad_by_name[] = {
    {"Lic Pro Controll", 14},  // Lic Pro Controller
    {"Nintendo Wireles", 14},  // Nintendo Wireless Gamepad
    {"Wireless Gamepad", 14},  // Wireless Gamepad
    {"Google LLC Stadi",  0},  // Google Stadia Controller
    {"Logitech Gamepad",  0},  // Logitech F710
    {"Luna Gamepad",      0},  // Luna Controller
    {"MOBAPAD Pro-HD",    0},  // Mobapad Chitu HD
    {"MOCUTE-053X-M51-",  0},  // Mocute 053X
    {"NVIDIA Corporati",  0},  // NVIDIA Controller
    {"Sony Computer En",  0},  // 8BitDo SN30 Pro Plus
    {"Sony Interactive",  0},  // Sony PlayStation Controller
    {"Sony PLAYSTATION",  0},  // PS3 Controller
    {"Wireless Control",  0},  // Sony PlayStation Controller
    {"Xbox 360 Wireles",  0},  // Xbox 360 Controller
    {"Xbox Wireless Co",  0},  // Xbox One Controller
    {"8BitDo 8BitDo Li",  1},  // 8BitDo Lite
    {"8BitDo 8BitDo Pr",  1},  // 8BitDo Pro 2
    {"8BitDo 8BitDo Re",  1},  // 8BitDo Receiver
    {"8BitDo Lite 2",     1},  // 8BitDo Lite 2
    {"8BitDo Lite SE",    1},  // 8BitDo Lite SE
    {"8BitDo Pro 2",      1},  // 8BitDo Pro 2
    {"8BitDo SN30 Pro+",  1},  // 8BitDo SN30 Pro Plus
    {"Generic X-Box pa",  3},  // Xbox Controller
    {"Microsoft X-Box ",  3},  // Xbox Controller
    {"X-Box Controller",  3},  // Retroid Pocket
    {"Retroid Pocket C",  4},  // Retroid Pocket
    {"Amazon Game Cont",  5},  // Luna Controller
    {"HORI CO.,LTD  PA",  8},  // Hori Gem Pad 3
    {"Performance Desi",  8},  // PDP PS3 Rock Candy Controller
    {"8Bitdo SF30 Pro",   9},  // 8BitDo SF30 Pro
    {"Linux 4.19.172 w", 11},  // Anbernic Handheld
    {"Odin Controller",  12},  // AYN Odin
    {"TGZ Controller",   16},  // TGZ Controller
};
#endif

//------ Encode gamepad layout to binary at compile-time ------
constexpr std::array<uint8_t, 20> encodeLine(const char* line) {
    std::array<uint8_t, 20> data = {};
    for(auto& d:data) d=0xff;

    int i=0;
    char c = *line;
    while(*line && i<data.size()) {
        uint8_t flags = 0;
        while(c==' ') {          c=*++line;}  // white-space
        if(c=='-') {flags|=0x80; c=*++line;}  // flip axis
        if(c=='b') {flags&=0x1F; c=*++line;}  // is button
        if(c=='a') {flags|=0x20; c=*++line;}  // is axis
        if(c=='h') {flags|=0x40; c=*++line;}  // is HAT
        uint8_t num=0;
        while(c>='0' && c<='9') {
            num=num*10+(c-'0');
            c=*++line;
        }
        data[i++]=num|flags;
    }
    return data;
}

template<std::size_t N>
constexpr auto encodeLines(const std::array<const char*, N>& lines) {
    std::array<std::array<uint8_t, 20>, N> result = {};
    for (std::size_t i = 0; i < N; ++i) {
        result[i] = encodeLine(lines[i]);
    }
    return result;
}

constexpr auto gamepad_layouts = encodeLines(gamepad_layout_list);
//-------------------------------------------------------------

//-------------------Return gamepad layout---------------------
static const std::array<uint8_t, 20>* get_gamepad_layout(uint16_t VID, uint16_t PID, uint8_t BUS, const char* name) {
    const std::array<uint8_t, 20>* layout = nullptr;
    for (const auto& entry : gamepad_index)
        if (entry.VID == VID && entry.PID == PID && entry.BUS == BUS)
            return &gamepad_layouts[entry.inx];
    for (const auto& entry : gamepad_by_name)
        if (strstr(name, entry.name))
            return &gamepad_layouts[entry.inx];
    return nullptr;
}
//-------------------------------------------------------------

#endif
